require: rubocop-rspec

Naming/AccessorMethodName:
  Enabled: false

Lint/ImplicitStringConcatenation:
  Enabled: false

Lint/EndAlignment:
 Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

AllCops:
  Exclude:
    - Gemfile
    - rspec-taken.gemspec
    - lib/taken/spec_samples/**/*
