Metrics/LineLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Lint/ImplicitStringConcatenation:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

AllCops:
  Exclude:
    - Gemfile
    - rspec-taken.gemspec
